#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use GasmxPricesUpdate\Command\GasmxPricesUpdate\GasmxPricesUpdateCommand;

$application = new Application('Gasmx Prices Update', '1.0');
$application->add(new GasmxPricesUpdateCommand());
$application->run();